# ArgoCD Applications for Dev Environment (단일 환경)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-wallet-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: nest-wallet
    app.kubernetes.io/instance: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: nest-wallet
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/nest-wallet.git
    targetRevision: develop
    path: helm-charts/nest-wallet
    helm:
      valueFiles:
        - values.yaml
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nest-wallet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
        - /status
