{{- range $name, $config := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nest-wallet.fullname" $ }}-{{ $name }}
  labels:
    {{- include "nest-wallet.labels" $ | nindent 4 }}
data:
  {{- toYaml $config | nindent 2 }}
---
{{- end }}
