{{- range $name, $config := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nest-wallet.fullname" $ }}-{{ $name }}
  labels:
    {{- include "nest-wallet.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $config }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
