apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nest-wallet-prod-nodepool
  annotations:
    karpenter.sh/do-not-evict: "true"
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
  template:
    metadata:
      labels:
        node.kubernetes.io/instance-type: spot
        karpenter.sh/capacity-type: spot
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [spot]
        - key: kubernetes.io/arch
          operator: In
          values: [arm64, amd64]
        - key: kubernetes.io/os
          operator: In
          values: [linux]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t4g.large
            - t4g.xlarge
            - c6g.large
            - c6g.xlarge
            - c6g.2xlarge
            - m6g.large
            - m6g.xlarge
            - m6g.2xlarge
        - key: topology.kubernetes.io/zone
          operator: In
          values: [ap-northeast-2a, ap-northeast-2c, ap-northeast-2d]
        - key: karpenter.sh/provisioner-name
          operator: DoesNotExist
      kubelet:
        systemReserved:
          cpu: 200m
          memory: 200Mi
        kubeReserved:
          cpu: 200m
          memory: 200Mi
        evictionHard:
          memory.available: 200Mi
          nodefs.available: 1%
        evictionSoft:
          memory.available: 400Mi
          nodefs.available: 1.5%
        evictionSoftGracePeriod:
          memory.available: 2m
          nodefs.available: 2m
        maxPods: 110
      taints:
        - key: spot
          value: "true"
          effect: NoSchedule
      startupTaints:
        - key: spot
          value: "true"
          effect: NoSchedule 