apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-toleration-config
  namespace: default
data:
  tolerations: |
    - key: "spot"
      value: "true"
      effect: "NoSchedule"
  nodeSelector: |
    node.kubernetes.io/instance-type: spot
    karpenter.sh/capacity-type: spot 