apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-wallet-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nest-wallet
  source:
    repoURL: https://github.com/blockbit-hama/nest-wallet.git
    targetRevision: develop
    path: helm-charts/nest-wallet
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-wallet-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nest-wallet
  source:
    repoURL: https://github.com/blockbit-hama/nest-wallet.git
    targetRevision: main
    path: helm-charts/nest-wallet
    helm:
      valueFiles:
        - values/production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
