apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nest-wallet
  namespace: argocd
  labels:
    app.kubernetes.io/name: nest-wallet-project
    app.kubernetes.io/part-of: argocd
  annotations:
    description: "Nest Wallet Application Project for GitOps Blue/Green Deployments"
spec:
  description: "Nest Wallet Application Project for GitOps Blue/Green Deployments"
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/blockbit-hama/nest-wallet.git'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  
  # Allowed Kubernetes resources
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: StorageClass
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: argoproj.io
      kind: ClusterRole
    - group: argoproj.io
      kind: ClusterRoleBinding
  
  # Allowed namespaced resources
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: ReplicaSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: argoproj.io
      kind: AnalysisRun
    - group: external-secrets.io
      kind: ExternalSecret
    - group: external-secrets.io
      kind: SecretStore
  
  # Sync windows 제거 (문제 해결을 위해)
  # syncWindows:
  #   # Dev 환경은 항상 허용
  #   - kind: allow
  #     schedule: '* * * * *'
  #     duration: 24h
  #     applications:
  #       - nest-wallet-dev
  #     namespaces:
  #       - dev
  #     clusters:
  #       - https://kubernetes.default.svc
  
  # RBAC policies
  roles:
    - name: admin
      description: Admin access to nest-wallet project
      policies:
        - p, proj:nest-wallet:admin, applications, *, nest-wallet/*, allow
        - p, proj:nest-wallet:admin, repositories, *, *, allow
        - p, proj:nest-wallet:admin, clusters, *, *, allow
        - p, proj:nest-wallet:admin, exec, create, nest-wallet/*, allow
      groups:
        - nest-wallet:admins
    
    - name: developer
      description: Developer access to nest-wallet project
      policies:
        - p, proj:nest-wallet:developer, applications, get, nest-wallet/*, allow
        - p, proj:nest-wallet:developer, applications, sync, nest-wallet/*, allow
        - p, proj:nest-wallet:developer, applications, action/*, nest-wallet/*, allow
        - p, proj:nest-wallet:developer, exec, create, nest-wallet/*, allow
        # Dev 환경 롤백 허용
        - p, proj:nest-wallet:developer, applications, rollback, nest-wallet/nest-wallet-dev, allow
      groups:
        - nest-wallet:developers
    
    - name: viewer
      description: Read-only access to nest-wallet project
      policies:
        - p, proj:nest-wallet:viewer, applications, get, nest-wallet/*, allow
        - p, proj:nest-wallet:viewer, applications, action/override, nest-wallet/*, deny
      groups:
        - nest-wallet:viewers
